# Generated by Django 3.2.9 on 2021-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211127_1557'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Close Issue'), (2, 'Open Issue'), (4, 'Administrator')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
    ]
