# Generated by Django 3.2.9 on 2022-01-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desc',
            new_name='description',
        ),
    ]
