# Generated by Django 3.2.9 on 2021-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211127_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACK-END', 'back-end'), ('FRONT-END', 'front-end'), ('IOS', 'IOS'), ('ANDROID', 'Android')], max_length=128),
        ),
    ]
